"""empty message

Revision ID: 4410dec0adfa
Revises: 6c34cde491e5
Create Date: 2025-04-11 14:00:39.622616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4410dec0adfa'
down_revision = '6c34cde491e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=250),
               existing_nullable=False)

    # ### end Alembic commands ###
